name: app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  dio: ^5.3.2
  #icon
  ionicons: ^0.2.2

  #state managment
  flutter_bloc: ^8.1.3

  #comparing dart objects
  equatable: ^2.0.5
  
  
 #Sevice Locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: ^1.4.2
  
  retrofit: ^4.0.1

  #Hooks
  flutter_hooks: ^0.20.1

  #chaced image
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true
  fonts:
      - family: Muli
        fonts:
          - asset: assets/fonts/muli/Muli.ttf
          - asset: assets/fonts/muli/Muli-Bold.ttf
            weight: 700
          - asset: assets/fonts/muli/Muli-Light.ttf
            weight: 300 

     

  